### ISSUE TITLE
Missing package "image_synthesis"

### ISSUE THREAD

**Issue by dto** [yangdongchao/Text-to-sound-Synthesis#1]
(specvqgan) dto@thexder:~/src/tss/Diffsound$ python evaluation/generate_samples_batch.py
Traceback (most recent call last):
  File "evaluation/generate_samples_batch.py", line 19, in <module>
    from image_synthesis.utils.io import load_yaml_config
ModuleNotFoundError: No module named 'image_synthesis'

Does not seem to be installable through anaconda.

**Comment by yangdongchao** [comment]
> 

Hi, I am sorry for this. I have been re-write this part code. You can refer to latest code.

**Comment by dto** [comment]
Ok, thank you! I am having trouble with paths such as /apdcephfs/share_1316500/donchaoyang/code3, should I simply set up a Linux mount point instead of changing the paths? What is the simplest way to enter new text and hear a result using the pretrained model? I'm excited about using this project for experimental musical sounds.

**Comment by yangdongchao** [comment]
> Ok, thank you! I am having trouble with paths such as /apdcephfs/share_1316500/donchaoyang/code3, should I simply set up a Linux mount point instead of changing the paths? What is the simplest way to enter new text and hear a result using the pretrained model? I'm excited about using this project for experimental musical sounds.

Hi, the path /apdcephf/  is my linux path, you must set it as your own path according to your machine.

**Comment by yangdongchao** [comment]
I will try to update a notebook file on google colab, which may solve the enviroment problem.
