### ISSUE TITLE
About CC_pretrained model

### ISSUE THREAD

**Issue by yizhidamiaomiao** [yangdongchao/Text-to-sound-Synthesis#11]
Dear authors,

When I try to reproduce your code, it seems that in your "Diffsound/running_command/run_train_audioset.py" file, you trained your model by loading a model called "--load_path OUTPUT/pretrained_model/CC_pretrained.pth".

Do we have to find and download CC_pretrained.pth? Where can we find it? 

Thanks a lot.

**Comment by yangdongchao** [comment]
> 

Hi, this model is not needed, load_path means that you can load a pre-trained model, but if you train your model from scratch, you donot need this.
