### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by mahmoudalismail** [yangdongchao/Text-to-sound-Synthesis#18]
Hi, 

The link for the latest pretrained models seems to have expired, is there another active link? 

> 2023/01/11 The latest pre-trained model on audioset have been released, please refer to PKU disk: [https://disk.pku.edu.cn:443/link/4908743A441B02235C8652742FE44949](https://disk.pku.edu.cn/link/4908743A441B02235C8652742FE44949)

Thanks!

**Comment by yangdongchao** [comment]
> Hi,
> 
> The link for the latest pretrained models seems to have expired, is there another active link?
> 
> > 2023/01/11 The latest pre-trained model on audioset have been released, please refer to PKU disk: [https://disk.pku.edu.cn:443/link/4908743A441B02235C8652742FE44949](https://disk.pku.edu.cn/link/4908743A441B02235C8652742FE44949)
> 
> Thanks!

https://disk.pku.edu.cn:443/link/87DE08BDA2521CB54F4911393EB36B4A
有效期限：2026-02-01 23:59

**Comment by JJHJGJH** [comment]
[https://disk.pku.edu.cn:443/link/87DE08BDA2521CB54F4911393EB36B4A](https://disk.pku.edu.cn/link/87DE08BDA2521CB54F4911393EB36B4A)
有效期限：2026-02-01 23:59这个似乎也过期了
